description: Reduce an exposure in hilo
tasks:
  isr:
    class: pfs.drp.stella.pipelines.IsrTask
    config:
      connections.ccdExposure: raw.exposure
  reduceExposure:
    class: pfs.drp.stella.reduceExposure.ReduceExposureTask
  mergeArms:
    class: pfs.drp.stella.mergeArms.MergeArmsTask

  # dmResiduals:
  # class: pfs.drp.qa.dmResiduals.DetectorMapResidualsTask
  # dmCombinedResiduals:
  #   class: pfs.drp.qa.dmCombinedResiduals.DetectorMapCombinedResidualsTask