description: Reduce an exposure in hilo
imports:
  - $DRP_STELLA_DIR/pipelines/reduceExposure.yaml
  - $DRP_QA_DIR/pipelines/drpQA.yaml
tasks:
  dmResiduals:
    class: pfs.drp.qa.dmResiduals.DetectorMapResidualsTask


