description: Reduce an exposure in hilo
tasks:
  isr:
    class: lsst.obs.pfs.isrTask.PfsIsrTask
  cosmicray:
    class: pfs.drp.stella.cosmicray.CosmicRayTask
  reduceExposure:
    class: pfs.drp.stella.reduceExposure.ReduceExposureTask
  mergeArms:
    class: pfs.drp.stella.mergeArms.MergeArmsTask

  # dmResiduals:
  # class: pfs.drp.qa.dmResiduals.DetectorMapResidualsTask
  # dmCombinedResiduals:
  #   class: pfs.drp.qa.dmCombinedResiduals.DetectorMapCombinedResidualsTask