# Just a placeholder from alerts
_warning: &WARNING
  alertType: trigger
  call: True
  alertFmt: '{value} is not OK !'

actors:
  drp: &DRPACTOR
    ingestStatus[statusStr]:
      <<: *WARNING
      alertFmt: '{value}'

  drp2:
    <<: *DRPACTOR

  iic:
    pfsConfig[instStatus]:
      <<: *WARNING
      alertFmt: 'pfsConfig.instStatus is not OK : {value}'