alerts:
  listen:
    interface: mhs-ics

  allowInvalid: 5  # allow consecutive invalid value without raising alerts.

  S:
    stsHost: sts-vm1.sum.subaru.nao.ac.jp
    parts: [ meb, peb, rough1, rough2, b1, r1, enu_sm1, b3, r3, enu_sm3 ]

  L:
    stsHost: localhost
    extendSTS: AIT@LAM
    parts: [ aitroom, rough1, b2, r2, n2, enu_sm2 ]