alerts:
  listen:
    interface: mhs-ics

  allowInvalid: 5  # allow consecutive invalid value without raising alerts.
  TIMEOUT: 600  # time limit(s) before declaring data source is in timeout.
  STS_DATA_RATE: 300 # default period(s) to push value to STS.
  S:
    stsHost: sts-vm1.sum.subaru.nao.ac.jp
    parts: [ meb, peb, rough1, rough2, b1, r1, n1, enu_sm1, b2, r2, n2, enu_sm2, b3, r3, n3, enu_sm3, b4, r4, n4, enu_sm4 ]

  L:
    stsHost: localhost
    extendSTS: AIT@LAM
    parts: [ aitroom, rough1]
