alerts:
  listen:
    interface: mhs-ics

  S:
    stsHost: sts-vm1.sum.subaru.nao.ac.jp
    parts: [ meb, peb, rough1, b1, r1, enu_sm1 ]

  L:
    stsHost: localhost
    parts: [ rough1, b2, r2, n2, enu_sm2 ]