connections: &CONNECTIONS
  listen:
    interface: bee-{cam}         # localhost is safest, if on same host

h4cam: &H4CAM
  <<: *CONNECTIONS

  controllers: &CONTROLLERS
    all: [ hxhal ]
    starting: [ hxhal ]

  logging:
    doRemote: true

  serialNumbers: &SERIAL_NUMBERS
    cryostat: -1
    fpa: -1
    sam: -1
    asic: -1
    h4: -1
  link: usb
  samRegisters: DefaultJadeRegisters_slow.rf
  asicFirmware: H4RG_IRP.mcd

  asicPreloadRegisters:
  asicPostloadRegisters:

  configName: coldIrp1
  voltages: &VOLTAGES
    VDD: 3.30
    VDDA: 3.30
    VBiasPower: 3.30

  dataRoot: /data/raw

  # SITE-indexed configuration.
  S:
    rampRoot: null
  L:
    rampRoot: /data/ramps
  J:
    rampRoot: /data/ramps

n1:
  <<: *H4CAM
  serialNumbers:
    <<: *SERIAL_NUMBERS
    cryostat: 2
    fpa: 2
    sam: 56
    asic: 247
    h4: 18660

n2:
  <<: *H4CAM
  serialNumbers:
    <<: *SERIAL_NUMBERS
    cryostat: 1
    fpa: 1
    sam: 59
    asic: 120
    h4: 18315

n3:
  <<: *H4CAM
  serialNumbers:
    <<: *SERIAL_NUMBERS
    cryostat: 3
    fpa: 4
    sam: 55
    asic: 119
    h4: 18321

n4:
  <<: *H4CAM
  serialNumbers:
    <<: *SERIAL_NUMBERS
    cryostat: 4
    fpa: 3
    sam: 57
    asic: 245
    h4: 18661

# The main IDG test dewar
n8:
  <<: *H4CAM
  serialNumbers:
    <<: *SERIAL_NUMBERS
    fpa: 5
    sam: 54
    asic: 248
    h4: 18734

# The NIR part of the b9 bench piepan, CCD DAQ, and NIR DAQ.
# Used for a portable ASIC+ROIC test FPA, and for electronics bench testing.
n9:
  <<: *H4CAM
  configName: warmIrp1
  serialNumbers:
    <<: *SERIAL_NUMBERS
    sam: 84
    asic: 229
    h4: ROIC
    
  listen:
    interface: bee-b9

# We were originally shipped six SAMs: 54-59 and five ASICs: 117-120,124.
#
# sam 58 was totally destroyed in a flood
# sam 54 ("damp SAM") was washed in a flood. Barely functional.
#
# asic 124 was also flooded, returned to Teledyne for rework, but declared dead and replaced with 229
