connections: &CONNECTIONS
  listen:
    interface: bee-{cam}         # localhost is safest, if on same host

h4cam: &H4CAM
  <<: *CONNECTIONS

  controllers: &CONTROLLERS
    all: [ hxhal ]
    starting: [ hxhal ]

  serialNumbers: &SERIAL_NUMBERS
    fpa: 0
    sam: 0
    asic: 0
    h4: 0
  link: usb
  samRegisters: DefaultJadeRegisters_slow.rf
  asicFirmware: H4RG_IRP.mcd

  asicPreloadRegisters:
  asicPostloadRegisters:

  configName: coldIrp1
  voltages: &VOLTAGES
    VDD: 3.30
    VDDA: 3.30
    VBiasPower: 3.30

n1:
  <<: *H4CAM
  serialNumbers:
    <<: *SERIAL_NUMBERS
    fpa: 2
    sam: 56
    asic: 117
    h4: 18660

n2:
  <<: *H4CAM

n3:
  <<: *H4CAM
  serialNumbers:
    <<: *SERIAL_NUMBERS
    fpa: 1
    sam: 54
    asic: 120
    h4: 18315
  voltages:
    <<: *VOLTAGES
    DSub: 0.600
    VReset: 0.250
    VBiasGate: 1.94
    Drain: 0.00
    CellDrain: 0.01

n8:
  <<: *H4CAM
  serialNumbers:
    <<: *SERIAL_NUMBERS
    fpa: 4
    sam: 57
    asic: 119
    h4: 18321

nLast:
  <<: *H4CAM
  serialNumbers:
    <<: *SERIAL_NUMBERS
    fpa: 3
    asic: 118
    sam: 55
    h4: 18661

n9:
  <<: *H4CAM
  configName: warmIrp1
  serialNumbers:
    <<: *SERIAL_NUMBERS
    sam: 58
    asic: 124

  listen:
    interface: bee-b9

# sam 59 was "bad"/"suspect"
