mcs:
  listen:
    interface: us-mcs    
    #interface: mcs

  db:
    hostname : db-ics
    dbname : opdb
    port : 5432
    username : pfs

  logging:
    baseLevel : 20
    cmdLevel : 20
    ioLevel : 20
    dispatchLevel : 30
    consoleLevel : 20

  centroidParams:
    boxCent: 14
    boxFind: 14
    centSigma: 25
    findSigma: 25
    fwhmx: 4
    fwhmy: 9
    matchRad: 20
    maxIt: 20
    nmax: 250
    nmin: 10
    threshFact: 4
    threshMode: full
    threshSigma: 4
    aperture: 8
    innerAnn: 20
    outerAnn: 24
    