mcs:
  listen:
    interface: us-mcs    
    #interface: mcs

  db:
    hostname : db-ics
    dbname : opdb
    port : 5432
    username : pfs

  logging:
    baseLevel : 20
    cmdLevel : 20
    ioLevel : 20
    dispatchLevel : 30
    consoleLevel : 20

  centroidParams:
    values:
    boxCent: 6
    boxFind: 10
    centSigma: 15
    findSigma: 35
    fwhmx: 0
    fwhmy: 0
    matchRad: 20
    maxIt: 20
    nmax: 250
    nmin: 10
    threshFact: 4
    threshMode: full
    threshSigma: 4
