pfsgui:
  listen:
    interface: localhost

  display:
    L:
      ait: [ rough1, dcb2, aten ]
      sm2: [ enu, b, r, n ]
    S:
      ait: [ ] # dcb,rough1,rough2
      sm1: [ enu, b, r ]
      sm3: [ enu, b, r ]
      pfi: [ peb, pfilamps ]
