xcu: &XCU
  listen:
    interface: bee-{cam}         # localhost is safest, if on same host

  controllers: &CONTROLLERS
    all: [ PCM, temps, turbo, ionpump, cooler, gatevalve, interlock ]
    starting: [ PCM, temps, turbo, ionpump, cooler, gatevalve, interlock ]

  cooler:
    host: cooler-{cam}
    port: 10001
    rejectLimit: 60

  interlock: &INTERLOCK
    port: /dev/ttyS1
    speed: 38400
    ignoreRoughPump: true

  PCM: &PCM
    host: pcm-{cam}
    port: 1000
    portNames: [ motors,gauge,cooler,temps,bee,fee,interlock,heaters ]
    gauge: new

  temps: &TEMPS
    host: temps-{cam}
    port: 1024

  turbo: &TURBO
    port: /dev/ttyS3
    speed: 9600

  ionpump: &IONPUMP
    host: moxa-{specName}
    port: 4001
    busId: null
    busIds: [ null, null ]
    pumpIds: [ null, null ]
    delay: 3.0
    maxPressure: 3.0e-5
    maxPressureDuringStartup: 5.0e-4
    spikeDelay: 3000

  # Which periodic monitors to start when a device is turned on.
  monitors: &MONITORS
    temps: 15
    turbo: 15
    ionpump: 15
    cooler: 15
    gatevalve: 60

  fpa: &FPA
    # Ugh.
    # A is vertical arm, others are clockwise w.r.t. that, for a human
    # facing the cryostat window.
    #
    # For NIR, A is down and dispersion is L-R on detector.
    # For vis, A is up and dispersion is U-D on detector.
    #
    # range is microns as determined by `tests fpaMotors findRange`
    # tilts is micron offsets to flatten focus plane.
    range: [300, 300, 300]
    tilts: [0, 0, 0]
    focus: 150

# There are two 2-pump ionpump controllers per 3-dewar spectrograph.
#
blue: &BLUE_XCU
  <<: *XCU

  ionpump: &BIONPUMP
    <<: *IONPUMP
    busIds: [ 1, 2 ]
    pumpIds: [ 1, 1 ]

red: &RED_XCU
  <<: *XCU

  ionpump: &RIONPUMP
    <<: *IONPUMP
    busIds: [ 1, 2 ]
    pumpIds: [ 2, 2 ]

nir: &NIR_XCU
  <<: *XCU

  controllers:
    <<: *CONTROLLERS
    all: [ PCM, temps, turbo, ionpump, cooler, gatevalve, interlock, cooler2 ]
    starting: [ PCM, temps, turbo, ionpump, cooler, gatevalve, interlock, cooler2 ]

  cooler2:
    host: cooler2-{cam}
    port: 10001
    rejectLimit: 60

  ionpump: &NIONPUMP
    <<: *IONPUMP
    busIds: [ 1, 2 ]
    pumpIds: [ 3, 3 ]

b1:
  <<: *BLUE_XCU
  fpa:
    <<: *FPA
    tilts: [15.3, 17.9, -33.2]
    focus: 146.4
b2:
  <<: *BLUE_XCU
  fpa:
    <<: *FPA
    tilts: [-2.3, 17.0, -14.7]
    focus: 219.6
b3:
  <<: *BLUE_XCU
  fpa:
    <<: *FPA
    tilts: [9.0, -0.5, -8.5]
    focus: 219.0
b4:
  <<: *BLUE_XCU
  fpa:
    <<: *FPA
    tilts: [10.2, -12.5, 2.3]
    focus: 106.0

r1:
  <<: *RED_XCU
  fpa:
    <<: *FPA
    tilts: [10.4, 12.6, -23.0]
    focus: 166.8
r2:
  <<: *RED_XCU
  fpa:
    <<: *FPA
    tilts: [-8.6, 21.3, -12.7]
    focus: 170.5
r3:
  <<: *RED_XCU
  fpa:
    <<: *FPA
    tilts: [8.9, -3.7, -5.2]
    focus: 201.9
r4:
  <<: *RED_XCU
  fpa:
    <<: *FPA
    tilts: [19.5, -20.7, 1.1]
    focus: 88.0

n1:
  <<: *NIR_XCU
  fpa:
    <<: *FPA
    range: [284.0, 293.0, 287.0]
    tilts: [-10, 45, -25]
    focus: 100.0
n2:
  <<: *NIR_XCU
  fpa:
    <<: *FPA
    range: [292.23, 278.05, 309.12]
    tilts: [1, -9, 7]
    focus: 150.0
n3:
  <<: *NIR_XCU
  fpa:
    range: [294.44, 288.12, 294.78]
    tilts: [10, 30, -50]
    focus: 170.0

n4:
  <<: *NIR_XCU
  fpa:
    <<: *FPA
    range: [283.60, 271.46, 306.38]
    tilts: [11, -11, -11]
    focus: 180.0

# IDG dewars
b9:
  <<: *BLUE_XCU
  controllers:
    <<: *CONTROLLERS
    all: [ PCM, temps, gatevalve, interlock ]
    starting: [ PCM, temps, gatevalve, interlock ]

  monitors:
    <<: *MONITORS
    turbo: 0
    ionpump: 0
    cooler: 0
    gatevalve: 0

n8:
  <<: *NIR_XCU
  controllers:
    <<: *CONTROLLERS
    all: [ PCM, temps, cooler]
    starting: [ PCM, temps, cooler]
r8:
  <<: *RED_XCU
  controllers:
    <<: *CONTROLLERS
    all: [ PCM, temps, cooler ]
    starting: [ PCM, temps, cooler ]
