xcu: &XCU
  listen:
    interface: bee-{cam}         # localhost is safest, if on same host

  controllers: &CONTROLLERS
    all: [ PCM, temps, turbo, ionpump, cooler, gatevalve, interlock ]
    starting: [ PCM, temps, turbo, ionpump, cooler, gatevalve, interlock ]

  cooler:
    host: cooler-{cam}
    port: 10001
    rejectLimit: 60

  interlock: &INTERLOCK
    port: /dev/ttyS1
    speed: 38400

  PCM: &PCM
    host: pcm-{cam}
    port: 1000
    portNames: [ motors,gauge,cooler,temps,bee,fee,interlock,heaters ]
    gauge: new

  temps: &TEMPS
    host: temps-{cam}
    port: 1024

  turbo: &TURBO
    port: /dev/ttyS3
    speed: 9600

  ionpump: &IONPUMP
    host: moxa-{specName}
    port: 4001
    busId: null
    busIds: [ null, null ]
    pumpIds: [ null, null ]
    delay: 3.0
    maxPressure: 3.0e-5
    maxPressureDuringStartup: 5.0e-4
    spikeDelay: 300

  # Which periodic monitors to start when a device is turned on.
  monitors: &MONITORS
    temps: 15
    turbo: 15
    ionpump: 15
    cooler: 15
    gatevalve: 60

  fpa: &FPA
    # Ugh.
    # A is vertical arm, others are clockwise w.r.t. that, for a human
    # facing the cryostat window.
    #
    # For NIR, A is down and dispersion is L-R on detector.
    # For vis, A is up and dispersion is U-D on detector.
    #
    # range is microns as determined by `tests fpaMotors findRange`
    # tilts is micron offsets to flatten focus plane.
    range: [300, 300, 300]
    tilts: [0, 0, 0]
    focus: 150

# There are two 2-pump ionpump controllers per 3-dewar spectrograph.
#
blue: &BLUE_XCU
  <<: *XCU

  ionpump: &BIONPUMP
    <<: *IONPUMP
    busId: 1
    busIds: [ 1, 1 ]
    pumpIds: [ 1, 2 ]

red: &RED_XCU
  <<: *XCU

  ionpump: &RIONPUMP
    <<: *IONPUMP
    busId: 1
    busIds: [ 1, 1 ]
    pumpIds: [ 3, 4 ]

nir: &NIR_XCU
  <<: *XCU

  controllers:
    <<: *CONTROLLERS
    all: [ PCM, temps, turbo, ionpump, cooler, gatevalve, interlock, cooler2 ]
    starting: [ PCM, temps, turbo, ionpump, cooler, gatevalve, interlock, cooler2 ]

  cooler2:
    host: cooler2-{cam}
    port: 10001
    rejectLimit: 60

  ionpump: &NIONPUMP
    <<: *IONPUMP
    busId: 2
    busIds: [ 2, 2 ]
    pumpIds: [ 1, 2 ]

b1:
  <<: *BLUE_XCU
b2:
  <<: *BLUE_XCU
b3:
  <<: *BLUE_XCU
b4:
  <<: *BLUE_XCU

  # JHU host hacks
  ionpump:
    <<: *BIONPUMP
    host: moxa-sm3
    busIds: [ 1, 1 ]
  roughActor: rough1

r1:
  <<: *RED_XCU
r2:
  <<: *RED_XCU
r3:
  <<: *RED_XCU
r4:
  <<: *RED_XCU

n1:
  <<: *NIR_XCU
  fpa:
    <<: *FPA
    range: [284.0, 293.0, 287.0]
    tilts: [-10, 45, -25]
    focus: 100.0
n2:
  <<: *NIR_XCU
  ionpump:
    <<: *NIONPUMP
    host: moxa-sm-nir
    port: 4004
    pumpIds: [ 3, 4 ]
  fpa:
    <<: *FPA
    range: [292.23, 278.05, 309.12]
    tilts: [1, -9, 7]
    focus: 150.0
  interlock:
    <<: *INTERLOCK
    ignoreRoughPump: true
n3:
  <<: *NIR_XCU
n4:
  <<: *NIR_XCU

# IDG dewars
b9:
  <<: *BLUE_XCU
  controllers:
    <<: *CONTROLLERS
    all: [ PCM, temps, gatevalve, interlock ]
    starting: [ PCM, temps, gatevalve, interlock ]

  monitors:
    <<: *MONITORS
    turbo: 0
    ionpump: 0
    cooler: 0
    gatevalve: 0

n8:
  <<: *NIR_XCU
  controllers:
    <<: *CONTROLLERS
    all: [ PCM, temps, gatevalve, cooler]
    starting: [ PCM, temps, gatevalve, cooler]
r8:
  <<: *RED_XCU
  controllers:
    <<: *CONTROLLERS
    all: [ PCM, temps, cooler ]
    starting: [ PCM, temps, cooler ]
